### ISSUE TITLE
Update Work and Bio pages

### ISSUE THREAD

**Issue by craigelloyd** [kevinpurdy/kevinpurdy.github.io#14]
Mr. Kevin Purdy no longer works at iFixit and now works at a neat website called Carbon Switch.

- On the "Work" page, the first sentence needs updated under the "Writing" section.
- On the "Bio" page, the last bullet needs updated. And maybe add another bullet talking about the new gig.

**Comment by kevinpurdy** [comment]
Wow. All I have is, wow.

**Comment by kevinpurdy** [comment]
Also, this is now fixed!
